version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: crash2cost-mongo
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-crash2cost}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-crash2cost_secret}
    volumes:
      - ./mongo-data:/data/db
    restart: always
